server:
  port: ${PORT:2333}       # Render automatically sets $PORT
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube:
        enabled: true
        cookies: "application/cookies.txt"   # YouTube search/play ke liye
      soundcloud: true      # Agar zarurat ho
      bandcamp: true        # Agar zarurat ho
      twitch: true          # Live streams
      vimeo: false          # Vimeo videos disabled
      http: true            # Generic HTTP audio sources
      local: false

    # Performance tuning
    bufferDurationMs: 4000        # low latency audio buffering
    frameBufferDurationMs: 1000   # smaller buffer for smoother streaming
    resumeDelay: 5000             # for resumable sessions
    maxPlayers: 50                # adjust based on bot load
    ratelimitTracks: 100          # concurrent track limit
    outputBufferDurationMs: 4000  # ✅ moved inside lavalink.server (no duplication)

plugins:
  - class: "com.github.topi314.lavalink.plugins.spotify.SpotifyPlugin"
    options:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      market: IN

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

logging:
  level: INFO
  file: false

# Advanced optional settings for speed & stability
playerUpdateInterval: 50       # smaller = more frequent updates
ytSearchPageCount: 1           # faster YouTube search, reduce pages scanned
