server:
  port: ${PORT:2333}       # Render automatically sets $PORT
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube:
        enabled: true
        cookies: "application/cookies.txt"   # YouTube search/play ke liye
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: false
      http: true
      local: false

    # Performance tuning
    bufferDurationMs: 4000
    frameBufferDurationMs: 1000
    resumeDelay: 5000
    maxPlayers: 50
    ratelimitTracks: 100
    outputBufferDurationMs: 4000

plugins:
  - class: "com.github.topi314.lavalink.plugins.spotify.SpotifyPlugin"
    options:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      market: IN

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

logging:
  level:
    root: INFO      # ✅ FIXED
  file: false

# Advanced optional settings for speed & stability
playerUpdateInterval: 50
ytSearchPageCount: 1
