# application.yml - optimized for free tier
server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: false
      http: true
    bufferDurationMs: 1000  # Reduce for free tier
    frameBufferDurationMs: 2000
    youtubeConfig:
      enabled: true
      retryOnFailure: true

sentry:
  dsn: ""
  environment: ""

plugins:
  youtube:
    enabled: true
    # Remove cookies requirement for now